id: A3FBB1A69
title: 'The Tambura’s Yearning Song of Devotion: A Prayer Summarizing Khandro Yeshe
  Tsogyal’s Life and Liberation'
type: translation
pechas:
- I5DCC3CEC
- I044C9C44
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:01:52.701493
  last_modified_at: 2023-01-04 12:01:52.701507
  collections:
  - Jamgön Kongtrul Lodrö Thaye Series
  - Works of Tibetan Masters
alignment_to_base:
  I5DCC3CEC/6E44: 2A89
  I044C9C44/5A5C: 2A89
